# Generated by Django 5.1.6 on 2025-03-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blogmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='created_at',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='categories',
            field=models.ManyToManyField(related_name='blogs', to='blogs.blogcategorymodel'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='blogs'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='blogs'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='long_description',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='tags',
            field=models.ManyToManyField(related_name='blogs', to='blogs.blogtagmodel'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
